### ISSUE TITLE
Find model Performance calculating method

### ISSUE THREAD

**Issue by Diva1010** [Diva1010/BitcoinAnalysis#2]
Find a way to calculate the performance of the model used.

**Comment by Diva1010** [comment]
Using the following matrices to evaluate model accuracy:
1) Root Mean Squared Error(RMSE) 
2) Mean Absolute Error(MAE)
3) R Squared (R2)
4) Adjusted R Squared

**Comment by kaimdx** [comment]
It is good to see you selected some metrics. You don't need to use all of them, as they are similar. 

In the final report, it is important to justify why the metrics are used. 

Also, it will be easier for comparison if any of the previous methods used these metrics to measure their performance.
