### ISSUE TITLE
Compare multiple models and compare performance

### ISSUE THREAD

**Issue by Diva1010** [Diva1010/BitcoinAnalysis#3]
Use different ML models to find the most accurate model to predict bitcoin price using performance parameter.

**Comment by kaimdx** [comment]
It will be useful to include in the comparison prediction of time points further in the future, not just one second ahead: for example 1 minute, 1 hour, 1 day, 1 week, and 1 month.

**Comment by Diva1010** [comment]
Comparing Below models:
1) Random Forest
2) NN (LSTM)
3) Linear Regression
4) XGBoost

**Comment by kaimdx** [comment]
Find out what dataset papers used, and use the same dataset in your model and compare the RMSE and MAE to see if there is any difference.
