### ISSUE TITLE
Document the existing model training and testing as a report.

### ISSUE THREAD

**Issue by kaimdx** [Diva1010/BitcoinAnalysis#5]
This is for me to understand the analysis that has been done, and later can be used in the final report.

**Comment by Diva1010** [comment]
[model report.docx](https://github.com/Diva1010/BitcoinAnalysis/files/3517517/model.report.docx)

Base document attached

**Comment by kaimdx** [comment]
Please see my comments in the attached file. 

It will be useful to write as you are writing the final report (so you don't need to write them again). In this case, the reader may not be familiar with machine learning, so a bit more background about the specific method (such as LSTM) is needed. 

Also, the thinking behind any important decision, such as choosing LSTM over other methods and the parameter settings, needs to be discussed as well. 

[model.report.comments.kai.docx](https://github.com/Diva1010/BitcoinAnalysis/files/3524960/model.report.comments.kai.docx)
