### ISSUE TITLE
Upload the jupyter notebook file (and data file)

### ISSUE THREAD

**Issue by kaimdx** [Diva1010/BitcoinAnalysis#7]
I still have error trying to run the code `model.py`, with both `python` and `ipython`.

I suspect that the reason is that code is copied from jupyther notebook as it has code such as `get_ipython().run_line_magic('matplotlib', 'inline')`.

In either case please add the jupyter notebook file to the git repository (the one you showed at the meeting?).

Also, please add any smaller data sample to the repository if there is any, though the `model.py` seems to load the data from an API.

**Comment by Diva1010** [comment]
Jupyter Notebook file has been uploaded.
Data sample is not required as the data is being fetched from the API

**Comment by kaimdx** [comment]
Thanks. I can run the jupyter notebook on my macbook. It does not take that long with 2000 data points. 

I noticed there are some empty cells, such as cell 2-4 and the cell above and below the dataframe table. Are these normal?

**Comment by Diva1010** [comment]
@kaimdx : Can you share the screenshot?

**Comment by kaimdx** [comment]
![image](https://user-images.githubusercontent.com/1853740/64103214-9c5b4c80-cd69-11e9-9175-bf48f3c1f9dc.png)
![image](https://user-images.githubusercontent.com/1853740/64103271-be54cf00-cd69-11e9-83a2-d720eb823c63.png)

**Comment by Diva1010** [comment]
yes. it's normal. just blanck cells added for some testing purpose. I will remove it at the final stage.
